# Generated by Django 5.0.6 on 2024-06-24 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Markatt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default=None, max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10, unique=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='inactive', max_length=8)),
            ],
            options={
                'db_table': 'markatt',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('uname', models.CharField(default=None, max_length=100)),
                ('uemail', models.EmailField(max_length=254, unique=True)),
                ('ucontact', models.CharField(max_length=10, unique=True)),
                ('upassword', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
