# Generated by Django 5.0.6 on 2024-06-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markatt',
            name='contact',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='markatt',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
