# Generated by Django 5.0.6 on 2024-06-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerform', '0002_alter_markatt_contact_alter_markatt_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
